### ISSUE TITLE
More of a review

### ISSUE THREAD

**Issue by spoofjack** [KyleBoyer/ADB-Clash-Royale-Bot#1]
Ive been running today on my S7 Edge.
I had to set screen res to 2560 and not 1980 like the readme suggested.

I wanted to say i like it so far.

1.) The sleep timer seems a little long to start off the battle. We are never the first to lay a card
2.) I found using high elixr cards with low elixr does not work. Because it spams the lower elixr level cards more often it never gathers enough elixr to drop the higher elixr cards
3.)It doesn't win a lot but im ok with that. (its just randomly dropping cards)
4.) Can you suggest a deck?
4b.) My thought was lower level elixr cards that can fight both air and ground battles and one surge
Something like BabyDrag/Minions/IceWiz/GobGang/Archers/MegaMin/E-Wiz/Hog

**Comment by KyleBoyer** [comment]
@spoofjack Does the screen res make a difference with any of the tap commands? Is it able to check and unlock chests properly?

I'm glad you like it!

1. Sometimes running hardwired(over USB) can help - as running the adb commands through the network can sometimes be slow due to router transmission speeds vs USB transmission speeds.
2. I also found that to be true, thats why I generally choose cards around the same elixer.
3. On a fresh account manually leveling up cards, I'm level 6 and hovering around 650-750 trophies. I think with higher level and cards it will have different sweet spots that it hovers around.
4. My account did manage to push into Arena 3 and get a chest, so I did unlock Barbarians from that. I never use throwables/spells. At 750ish trophies and level 6 I am currently using:
    - Lvl 1 : Baloon
    - Lvl 1 : Barbarians
    - Lvl 7 : Knight
    - Lvl 6 : Minions
    - Lvl 2 : Baby Dragon
    - Lvl 2 : Prince
    - Lvl 4 : Musketeer
    - Lvl 4 : Valkyrie

I curious to possibly make some of the code run on the device itself and send a status back to the computer to maybe fix some of the slowness with recognizing pixel colors and transmission speeds. This may be far out though as I'm still fine tuning everything.

**Comment by spoofjack** [comment]
Screen Res is working set to 2560 Chests and Card Drops
I'm running hardwired.
Keep up the good work. Its something fun to mess with around with my alt accounts.
Got three as of now Main is legendary arena level 11
The others are level 10 and Jungle

**Comment by spoofjack** [comment]
On a side note

(Rooted? - Unsure) Android Device

Root is not needed :)

Just make sure to have USB Debugging enabled in Developer Options
